### ISSUE TITLE
[net-snmp-5.8.1pre2] Restarting snmpd produces warning "Warning: Unknown token: ifXTable"

### ISSUE THREAD

**Issue by tanstafel** [net-snmp/net-snmp#137] opened 2020-06-18 14:04 UTC
When restarting snmpd 5.8.1pre2 it produces warning "Warning: Unknown token: ifXTable". This is likely caused by postponing ifXTable setup to be after reading the snmpd config. I guess that parsing the persistent settings (where this warning comes from) happen earlier.

**Comment by EZenderink** [comment] 2020-06-23 07:56
I believe something similar is happening in issue #99

**Comment by ColdForest** [comment] 2020-07-09 15:51
This indeed appears to be a duplicate of #99.

**Comment by rstory** [comment] 2020-07-13 15:27
yep, closing as duplicate..

**Closed by rstory** 2020-07-13 15:27 UTC
Labels: duplicate

**Comment by rstory** [comment] 2020-07-13 17:04
Just for completeness since original poster might not be following #9: I've committed a fix that works for me (https://github.com/net-snmp/net-snmp/commit/e772b8017d7e235437a45622bf8aa05f3ef3d084) in V5-8-patches.. Can anyone test and confirm it works for them too?  (Please respond in #99)
